# Program to evaluate the patches

# Written by Marley Sudbury (1838838)
# for CM3203 One Semester Individual Project

# Confidences are encoded as R G B
# (100, 0, 0) = 100% positive
# (0, 100, 0) = 100% negative
# (50, 50, 0) = 50% positive, 50% negative
# (0, 0, 0) = background

from PIL import Image
import shapely

# Load the image
mask_path = "mask.png"  # PNG file with mask generated by classify.py
annotation_path = ""  # GeoJSON file containing ground truth annotation
scale = None  # The scale between the mask and the annotation (true slide size)
with Image.open(mask_path) as im:
    im.show()
    pass

    for row in im:
        for pixel in row:
            if pixel[0] > 50:
                # Classified as positive
                pass
            elif pixel[1] > 50:
                # Classified as negative
                pass
            elif pixel == (0, 0, 0):
                # Classified as background
                pass
